services:
  backend:
    container_name: django-backend
    image: sergeyvernyk/django-backend-2:${IMAGE_TAG}
    user: django-user
    ports:
      - 8000:8001
    volumes:
      - backend_static:/app/static
    env_file: .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker -w 1 --bind :8001
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:14.6-alpine
    container_name: postgres-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer-postgres
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  nginx:
    image: nginx:1.27.4-alpine
    container_name: nginx-backend
    env_file: .env
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
    volumes:
      # основний nginx конфіг
      - ./config/deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # скрипт очікування бекенду перед стартом nginx
      - ./wait-for-backend.sh:/wait-for-backend.sh
      # django static files
      - backend_static:/app/static
      # SSL сертифікати Let's Encrypt
      - certs:/etc/letsencrypt
      # тимчасова папка для ACME challenge для certbot
      - certbot:/var/www/certbot
    # спочатку чекаємо backend, потім стартує nginx
    command: sh /wait-for-backend.sh
    depends_on:
      - backend
    networks:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      # HTTPS сертифікати зберігаються тут же, що й у nginx
      - certs:/etc/letsencrypt
      # webroot для ACME challenge
      - certbot:/var/www/certbot
    entrypoint: ["sh", "-c"]
    # сертифікат отримується вручну окремою командою
    command: "echo 'Skipping certbot run'"
    depends_on:
      - nginx

volumes:
  postgres_data:
    driver: local
  # volume для challenge файлів 
  certbot:
    driver: local
  # volume для SSL сертифікатів
  certs:
    driver: local
  backend_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/drf_deploy_project_static

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1452
