# визначаємо upstream для бекенду — nginx знає, куди проксувати запити
upstream backend {
    server backend:8001;  # тут ім'я контейнера та порт Django/gunicorn
}

# HTTP сервер для постійного редіректу на HTTPS і для certbot (отримання сертифікату HTTPS)
server {
    listen          80;               # слухаємо порт 80 для HTTP
    server_name     proxman.pp.ua;    # домен, на який відповідаємо

    # ACME challenge для certbot (отримання SSL сертифікату)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;    # шлях до тимчасових файлів certbot
        allow all;                # дозволяємо доступ з інтернету
    }

    # Все інше — просто редірект на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS сервер
server {
    listen                  443 ssl;          # слухаємо порт 443 для HTTPS
    server_name             proxman.pp.ua;    # домен

    # Шляхи до сертифікатів в системі, отриманих через certbot
    ssl_certificate         /etc/letsencrypt/live/proxman.pp.ua/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/proxman.pp.ua/privkey.pem;

    # Заголовки, які передаємо бекенду
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    # Основний бекенд (Django/Gunicorn)
    location / {
       proxy_pass       http://backend;  # проксі до upstream backend
    }

    # Adminer для роботи з базою
    location /adminer/ {
        proxy_pass      http://adminer:8080;
    }

    # шлях до статичних файлів, зібраних командою 'manage.py collectstatic'
    location /static/ {
       alias        /app/static/;  # шлях до зібраних статичних файлів
    }
}